INSERT INTO TB_WORKER (DAILY_INCOME, NAME) VALUES (325.0, 'Andre');
INSERT INTO TB_WORKER (DAILY_INCOME, NAME) VALUES (257.0, 'Maria');
INSERT INTO TB_WORKER (DAILY_INCOME, NAME) VALUES (197.0, 'Ana');
INSERT INTO TB_WORKER (DAILY_INCOME, NAME) VALUES (154.0, 'Ramon');